// <auto-generated />
using System;
using Bookify.Services.Booking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookify.Services.Booking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260810160538_AddIdempotencyRequests")]
    partial class AddIdempotencyRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookify.Services.Booking.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RentableUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("rentable_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("PropertyId", "Status")
                        .HasDatabaseName("ix_bookings_property_id_status");

                    b.HasIndex("RentableUnitId", "Status")
                        .HasDatabaseName("ix_bookings_rentable_unit_id_status");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_bookings_cancellation_consistency", "(status = 'Cancelled' AND cancellation_reason IS NOT NULL) OR (status <> 'Cancelled' AND cancellation_reason IS NULL)");

                            t.HasCheckConstraint("ck_bookings_guest_count", "guest_count > 0");

                            t.HasCheckConstraint("ck_bookings_status", "status IN ('PendingApproval', 'PendingPayment', 'Paid', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("ck_bookings_stay_period", "check_out_date > check_in_date");
                        });
                });

            modelBuilder.Entity("Bookify.Services.Booking.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("CheckInTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly>("CheckOutTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_out_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("Bookify.Services.Booking.Domain.Properties.RentableUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxBaseGuests")
                        .HasColumnType("integer")
                        .HasColumnName("max_base_guests");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_rentable_units");

                    b.HasIndex("PropertyId", "Type")
                        .HasDatabaseName("ix_rentable_units_property_id_type");

                    b.ToTable("rentable_units", null, t =>
                        {
                            t.HasCheckConstraint("ck_rentable_units_base_guests_capacity", "max_base_guests <= maximum_capacity");

                            t.HasCheckConstraint("ck_rentable_units_maximum_capacity", "maximum_capacity > 0");

                            t.HasCheckConstraint("ck_rentable_units_type", "type IN ('EntireProperty', 'Room')");
                        });
                });

            modelBuilder.Entity("Bookify.Services.Booking.Infrastructure.Persistence.Idempotency.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_requests_expires_at");

                    b.HasIndex("HttpMethod", "Endpoint", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_requests_scope_key");

                    b.ToTable("idempotency_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_requests_completion", "(\n    status = 'InProgress'\n    AND status_code IS NULL\n)\nOR\n(\n    status = 'Completed'\n    AND status_code IS NOT NULL\n)");

                            t.HasCheckConstraint("ck_idempotency_requests_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_idempotency_requests_status", "status IN\n(\n    'InProgress',\n    'Completed'\n)");

                            t.HasCheckConstraint("ck_idempotency_requests_status_code", "status_code IS NULL\nOR\n(\n    status_code >= 100\n    AND status_code <= 599\n)");
                        });
                });

            modelBuilder.Entity("Bookify.Services.Booking.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Bookify.Services.Booking.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_properties_property_id");

                    b.HasOne("Bookify.Services.Booking.Domain.Properties.RentableUnit", null)
                        .WithMany()
                        .HasForeignKey("RentableUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_rentable_units_rentable_unit_id");

                    b.OwnsOne("Bookify.Services.Booking.Domain.Bookings.ValueObjects.StayPeriod", "StayPeriod", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("CheckInDate")
                                .HasColumnType("date")
                                .HasColumnName("check_in_date");

                            b1.Property<DateOnly>("CheckOutDate")
                                .HasColumnType("date")
                                .HasColumnName("check_out_date");

                            b1.HasKey("BookingId");

                            b1.HasIndex("CheckInDate", "CheckOutDate")
                                .HasDatabaseName("ix_bookings_check_in_date_check_out_date");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Bookify.Services.Booking.Domain.Shared.ValueObjects.GuestCount", "GuestCount", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("guest_count");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("GuestCount")
                        .IsRequired();

                    b.Navigation("StayPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookify.Services.Booking.Domain.Properties.RentableUnit", b =>
                {
                    b.HasOne("Bookify.Services.Booking.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rentable_units_properties_id");
                });
#pragma warning restore 612, 618
        }
    }
}
